apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: bookstore
data:
  USERS_SERVICE_URL: "http://users-service:8001"
  BOOKS_SERVICE_URL: "http://books-service:8002"
  ORDERS_SERVICE_URL: "http://orders-service:8003"
  PAYMENTS_SERVICE_URL: "http://payments-service:8004"
  REVIEWS_SERVICE_URL: "http://reviews-service:8005"
  CORS_ALLOW_ALL_ORIGINS: "true"
  DEBUG: "false"

